
### Get Home Route
GET http://localhost:8080/

### Get Professional Route
GET http://localhost:8080/professional

### Get all contacts
GET http://localhost:8080/contacts

### Get all contacts (prettyPrint)
GET http://localhost:8080/contacts?prettyPrint=true

### Get a single contact by ID
GET http://localhost:8080/contacts/65b029df100c1a9fa3ae5a3c

### Get contacts by favorite color green
GET http://localhost:8080/contacts/color/green

### Get contacts by favorite color blue
GET http://localhost:8080/contacts/color/Blue

### Get contacts by favorite color pink
GET http://localhost:8080/contacts/color/pink

### Get contacts by favorite color red
GET http://localhost:8080/contacts/color/red

### Get contacts by birthday month
GET http://localhost:8080/contacts/b-month/02

### Add a new contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "favoriteColor": "Blue",
  "birthday": "1990-01-01"
}

### Update a contact
PUT http://localhost:8080/contacts/65b5ac1883d95c86f58851a0
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@example.com",
  "favoriteColor": "yellow",
  "birthday": "1990-01-01"
}

### Delete a contact
DELETE http://localhost:8080/contacts/65b5ac4883d95c86f58851a2

// PRODUCTION ROUTES:

### Get Home Route
GET https://cse341-03-web-service.onrender.com/

### Get Professional Route
GET https://cse341-03-web-service.onrender.com/professional

### Get all contacts
GET https://cse341-03-web-service.onrender.com/contacts

### Get all contacts (prettyPrint)
GET https://cse341-03-web-service.onrender.com/contacts?prettyPrint=true



### Get a contact by ID
GET https://cse341-03-web-service.onrender.com/contacts/65b5ac1883d95c86f58851a0

### Get contacts by first name
GET https://cse341-03-web-service.onrender.com/contacts/f-name/evelyn

### Get contacts by favorite color
GET https://cse341-03-web-service.onrender.com/contacts/color/green

### Get contacts by birthday month
GET https://cse341-03-web-service.onrender.com/contacts/b-month/02

### Add a new contact
POST https://cse341-03-web-service.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Freddy",
  "lastName": "Alger",
  "favoriteColor": "Red",
  "birthday": "1997-08-02"
}

### Update a contact
PUT https://cse341-03-web-service.onrender.com/contacts/65b5ac1883d95c86f58851a0
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "jd@gmail.com",
  "favoriteColor": "yellow",
  "birthday": "1990-01-01"
}

### Delete a contact
DELETE https://cse341-03-web-service.onrender.com/contacts/65b5ac4883d95c86f58851a2










// SAMPLE CONTACTS:
# {
# "_id": "65b5ac4883d95c86f58851a2",
# "firstName": "Del",
# "lastName": "Me",
# "email": "@test.com",
# "favoriteColor": "Brown",
# "birthday": "01/18/2005"
# },