
### Get Home Route
GET http://localhost:8080/

### Get Professional Route
GET http://localhost:8080/professional

### Get all contacts
GET http://localhost:8080/contacts

### Get a contact by ID
GET http://localhost:8080/contacts/65b029df100c1a9fa3ae5a3c


### Get contacts by favorite color green
GET http://localhost:8080/contacts/color/green

### Get contacts by favorite color blue
GET http://localhost:8080/contacts/color/Blue

### Get contacts by favorite color pink
GET http://localhost:8080/contacts/color/pink


### Get contacts by favorite color red
GET http://localhost:8080/contacts/color/red

### Get contacts by birthday month
GET http://localhost:8080/contacts/b-month/02